service: todo-app-example

custom:
  tableName: 'todo-app-${self:provider.stage}1'
  index1: "GSI1"
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
       - { "Fn::GetAtt": ["ToDoAppDynamoDBTable", "Arn" ] }
       - Fn::Join:
         - "/"
         -
           - { "Fn::GetAtt": ["ToDoAppDynamoDBTable", "Arn" ] }
           - "index/*"
  environment:
    TODO_APP_TABLE: ${self:custom.tableName}
    TODO_APP_GSI_1: ${self:custom.index1}

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  ${file(functions/api-endpoints.yml)}

resources:
  ${file(resources/dynamodb-table.yml)}
